brain_substructure: BrStem
cache_dir: /vol/bitbucket/rrr2417/deepscm_data_cache
cf_elbo_type: -1
cheb_k: 10
csv_path: /vol/biomedic3/bglocker/brainshapes/ukb21079_extracted.csv
data_dir: /vol/biomedic3/bglocker/brainshapes
decoder_cov_rank: 10
decoder_type: normal
experiment: SVIExperiment
filters:
- 16
- 32
- 64
- 128
gpu: 1
img_shape:
- 642
- 3
in_channels: 3
l2: 0.0
latent_dim: 64
logstd_init: -5
lr: 0.0001
model: ConditionalVISEM
num_sample_particles: 32
num_svi_particles: 1
pgm_lr: 0.001
pooling_factor: 2
reload_mesh_path: true
sample_mesh_interval: 1
template_path: /vol/biomedic3/bglocker/brainshapes/5026976/T1_first-BrStem_first.vtk
test_batch_size: 50
train_batch_size: 256
train_test_split: 0.8
train_val_split: 0.1
use_amsgrad: false
use_cf_guide: false
validate: false
